from __future__ import annotations

from .app_settings import default_app_settings, load_app_settings, save_app_settings  # noqa: F401
from .settings import (  # noqa: F401
    API_KEY_FILE,
    APP_NAME,
    APP_SETTINGS_FILE,
    APP_VERSION,
    CODEC_MAP,
    CODEC_PARAMS,
    DATA_DIR,
    DEFAULT_CODEC,
    DEFAULT_OUTPUT_DIR,
    DEFAULT_SPEED,
    DEFAULT_WINDOW_HEIGHT,
    DEFAULT_WINDOW_WIDTH,
    FFMPEG_COMMAND,
    FFMPEG_MIN_VERSION,
    FLUENT_ACCENT_HEX,
    FLUENT_ENABLED,
    FORMAT_EXTENSION_MAP,
    FORMAT_FILTER_MAP,
    GPT_4O_MINI_TTS_MODEL,
    LOG_FILE,
    LOGGING_FORMAT,
    LOGGING_LEVEL,
    MAX_CHUNK_SIZE,
    MAX_RETRIES,
    MAX_SPEED,
    MIN_SPEED,
    OBFUSCATION_KEY,
    OPENAI_BASE_URL,
    OPENAI_TIMEOUT,
    OUTPUT_BITRATE,
    OUTPUT_CHANNELS,
    OUTPUT_SAMPLE_RATE,
    PARALLELISM,
    PRESETS_FILE,
    RETRY_DELAY,
    STREAM_FORMAT,
    TTS_FORMATS,
    TTS_MODELS,
    TTS_VOICES,
    USE_KEYRING,
    ensure_directories,
    env_snapshot,
)

_THEME_EXPORTS = {
    "DARK_THEME",
    "LIGHT_THEME",
    "apply_fusion_dark",
    "build_stylesheet",
}


def __getattr__(name: str):
    if name in _THEME_EXPORTS:
        from .theme import DARK_THEME, LIGHT_THEME, apply_fusion_dark, build_stylesheet

        return {
            "DARK_THEME": DARK_THEME,
            "LIGHT_THEME": LIGHT_THEME,
            "apply_fusion_dark": apply_fusion_dark,
            "build_stylesheet": build_stylesheet,
        }[name]
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = [
    "APP_NAME",
    "APP_VERSION",
    "APP_SETTINGS_FILE",
    "DATA_DIR",
    "LOG_FILE",
    "PRESETS_FILE",
    "API_KEY_FILE",
    "DEFAULT_OUTPUT_DIR",
    "OPENAI_TIMEOUT",
    "OPENAI_BASE_URL",
    "TTS_MODELS",
    "GPT_4O_MINI_TTS_MODEL",
    "TTS_VOICES",
    "TTS_FORMATS",
    "DEFAULT_SPEED",
    "MIN_SPEED",
    "MAX_SPEED",
    "MAX_CHUNK_SIZE",
    "MAX_RETRIES",
    "RETRY_DELAY",
    "STREAM_FORMAT",
    "PARALLELISM",
    "OBFUSCATION_KEY",
    "USE_KEYRING",
    "DEFAULT_WINDOW_WIDTH",
    "DEFAULT_WINDOW_HEIGHT",
    "FLUENT_ENABLED",
    "FFMPEG_COMMAND",
    "FFMPEG_MIN_VERSION",
    "FORMAT_EXTENSION_MAP",
    "FLUENT_ACCENT_HEX",
    "FORMAT_FILTER_MAP",
    "CODEC_MAP",
    "DEFAULT_CODEC",
    "OUTPUT_SAMPLE_RATE",
    "OUTPUT_CHANNELS",
    "OUTPUT_BITRATE",
    "CODEC_PARAMS",
    "LOGGING_LEVEL",
    "LOGGING_FORMAT",
    "ensure_directories",
    "env_snapshot",
    "default_app_settings",
    "load_app_settings",
    "save_app_settings",
    "DARK_THEME",
    "LIGHT_THEME",
    "apply_fusion_dark",
    "build_stylesheet",
]
