name: build
on:
  push:
    tags:
      - "v*"
jobs:
  bundle:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
      - name: Install build deps
        run: |
          python -m pip install -U pip
          pip install .[dev]
      - name: Build
        run: |
          pyinstaller --noconfirm openai_tts.spec
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenAI-TTS-${{ runner.os }}-${{ github.ref_name }}
          path: dist/**
